### ISSUE TITLE
App crashes right after launching with this module.

### ISSUE THREAD

**Issue by yomybaby** [appcelerator-modules/ti.compression#6]
Environment 
- Android API 23(6.0)
- TiSDK 5.0.2.GA
- Android Device : Nexus 5 (6.0)

App crashes right after launching with this module. There is no error message.

**Comment by ashcoding** [comment]
Just adding additional information for the crash from logcat:-
```
11-16 21:45:55.431  9215  9228 E AndroidRuntime: FATAL EXCEPTION: KrollRuntimeThread
11-16 21:45:55.431  9215  9228 E AndroidRuntime: Process: sg.com.appcelerator, PID: 9215
11-16 21:45:55.431  9215  9228 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/sg.com.appcelerator-2/lib/arm/libti.compression.so: has text relocations
11-16 21:45:55.431  9215  9228 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary(Runtime.java:372)
11-16 21:45:55.431  9215  9228 E AndroidRuntime: 	at java.lang.System.loadLibrary(System.java:1076)
11-16 21:45:55.431  9215  9228 E AndroidRuntime: 	at org.appcelerator.kroll.runtime.v8.V8Runtime.loadExternalModules(V8Runtime.java:132)
11-16 21:45:55.431  9215  9228 E AndroidRuntime: 	at org.appcelerator.kroll.runtime.v8.V8Runtime.initRuntime(V8Runtime.java:99)
11-16 21:45:55.431  9215  9228 E AndroidRuntime: 	at org.appcelerator.kroll.KrollRuntime.doInit(KrollRuntime.java:185)
11-16 21:45:55.431  9215  9228 E AndroidRuntime: 	at org.appcelerator.kroll.KrollRuntime$KrollRuntimeThread.run(KrollRuntime.java:109)
```
Crash will be resolved when recompiled with latest NDK and SDK.
